import { reactive } from 'vue';
import { useI18n } from '/@/hooks/web/useI18n';
const { t } = useI18n();
const menuListRight = reactive([
  // {
  //   No: 'DataV_HomeAdmin',
  //   Name: '首页',
  //   Url: '/WF/Comm/DataV',
  //   FileUrl: '/src/WF/views/GenerList.vue',
  //   Path: 'GenerList',
  //   Paras: '?EnName=DataV_HomeAdmin',
  //   Icon: 'icon-pie-chart',
  //   Enable: 1,
  //   ShowBadge: false,
  // },

  {
    No: 'EntityDemo',
    Name: '实体Demo',
    Url: '/WF/GL/TSDemo',
    FileUrl: '/src/WF/views/GenerList.vue',
    Path: 'GenerList',
    Paras: '?EnName=GL_TSClassDemo',
    Icon: 'icon-rocket',
    Enable: 1,
    ShowBadge: false,
    Desc: '驰骋自研ORM，快速实现CRUD',
  },
  {
    No: 'System',
    Name: '低代码',
    Url: '/WF/GL/System',
    FileUrl: '/src/WF/views/GenerList.vue',
    Path: 'GenerList',
    Paras: '?EnName=GL_System',
    Icon: 'icon-puzzle',
    Enable: 1,
    ShowBadge: false,
    // Desc: '内部升级中，暂时禁用',
  },
  {
    No: 'FlowPage',
    Name: '流程',
    Url: '/WF/Comm/TreeEns?EnName=TreeEns_FlowSort2Flow',
    FileUrl: '/src/WF/Comm/TreeEns',
    Path: 'TreeEns',
    Paras: '?EnName=TreeEns_FlowSort2Flow',
    Icon: 'icon-organization',
    Enable: 1,
    ShowBadge: false,
  },
  {
    No: 'FrmPage',
    Name: '表单',
    Url: '/WF/Comm/TreeEns?EnName=TreeEns_FrmSort2Frm',
    FileUrl: '/src/WF/Comm/TreeEns',
    Path: 'TreeEns',
    Paras: '?EnName=TreeEns_FrmSort2Frm',
    Icon: 'icon-diamond',
    Enable: 1,
    ShowBadge: false,
  },
  {
    No: 'Organization',
    Name: '组织',
    Url: '/WF/Comm/TreeEns?EnName=TreeEns_Dept2Emp',
    FileUrl: '/src/WF/Comm/TreeEns',
    Path: 'TreeEns',
    Paras: '?EnName=TreeEns_Dept2Emp',
    Icon: 'icon-people',
    Enable: 1,
    ShowBadge: false,
  },
  {
    No: 'DBSrc',
    Name: '数据源',
    Url: '/WF/Comm/TreeEns?EnName=TreeEns_DBSrc',
    FileUrl: '/src/WF/views/GenerList.vue',
    Path: 'GenerList',
    Paras: '?EnName=TreeEns_DBSrc',
    Icon: 'icon-settings',
    Enable: 1,
    ShowBadge: false,
  },
  {
    No: 'GL_Msg',
    Name: '消息',
    Url: '/WF/GL/Msg',
    FileUrl: '/src/WF/views/GenerList.vue',
    Path: 'En',
    Paras: '?EnName=GL_Msg',
    Icon: 'icon-bubbles',
    Enable: 1,
    ShowBadge: true,
  },
  // {
  //   No: 'GL_EntitySafe',
  //   Name: '安全',
  //   Url: '/WF/GL/GL_EntitySafe',
  //   FileUrl: '/src/WF/views/GenerList.vue',
  //   Path: 'En',
  //   Paras: '?EnName=GL_EntitySafe',
  //   Icon: 'icon-umbrella',
  //   Enable: 1,
  // },
]);

export default menuListRight;
